server:
  port: 8888

mybatis-plus:
  mapper-locations: classpath:dao/*.xml
   #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.mybatis.entity
  configuration:
    # 开启驼峰功能
    map-underscore-to-camel-case: true
  global-config:
    # 驼峰下划线转换
    db-column-underline: true
    id-type: 1
    # 数据库大写下划线转换
    capital-mode: true
    #刷新mapper 调试神器
    refresh-mapper: true

pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/ftpServer?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://localhost:3306/phone_message?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    caffeine:
      spec: maxmumSize=500, expireAfterWrite=5s
    type: caffeine
    cache-names:
      - getUserById
      - listCustomers